version: '3'
networks:
  backend:
    driver: bridge

services:

### Workspace ##################################################
  workspace:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USERNAME
    container_name: workspace
    restart: unless-stopped
    volumes:
      - ~:/home/${USERNAME}
    networks:
      - backend